//
// Created by amartinez on 1/4/2024.
//

#ifndef PRACTICO1_EJ2COMPETENCIASETCACHE_H
#define PRACTICO1_EJ2COMPETENCIASETCACHE_H

#endif //PRACTICO1_EJ2COMPETENCIASETCACHE_H


void ej2CompetenciaSetCache();